/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package demo;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ExamplePerson extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2744636100838045267L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ExamplePerson\",\"namespace\":\"demo\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"username\",\"type\":[\"string\",\"null\"]},{\"name\":\"wtf\",\"type\":[\"string\",\"int\"]},{\"name\":\"maybeWtf\",\"type\":[\"string\",\"int\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ExamplePerson> ENCODER =
      new BinaryMessageEncoder<ExamplePerson>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ExamplePerson> DECODER =
      new BinaryMessageDecoder<ExamplePerson>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ExamplePerson> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ExamplePerson> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ExamplePerson>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ExamplePerson to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ExamplePerson from a ByteBuffer. */
  public static ExamplePerson fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int id;
  @Deprecated public java.lang.CharSequence username;
  @Deprecated public java.lang.Object wtf;
  @Deprecated public java.lang.Object maybeWtf;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ExamplePerson() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param username The new value for username
   * @param wtf The new value for wtf
   * @param maybeWtf The new value for maybeWtf
   */
  public ExamplePerson(java.lang.Integer id, java.lang.CharSequence username, java.lang.Object wtf, java.lang.Object maybeWtf) {
    this.id = id;
    this.username = username;
    this.wtf = wtf;
    this.maybeWtf = maybeWtf;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return username;
    case 2: return wtf;
    case 3: return maybeWtf;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: username = (java.lang.CharSequence)value$; break;
    case 2: wtf = (java.lang.Object)value$; break;
    case 3: maybeWtf = (java.lang.Object)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }


  /**
   * Gets the value of the 'username' field.
   * @return The value of the 'username' field.
   */
  public java.lang.CharSequence getUsername() {
    return username;
  }


  /**
   * Gets the value of the 'wtf' field.
   * @return The value of the 'wtf' field.
   */
  public java.lang.Object getWtf() {
    return wtf;
  }


  /**
   * Gets the value of the 'maybeWtf' field.
   * @return The value of the 'maybeWtf' field.
   */
  public java.lang.Object getMaybeWtf() {
    return maybeWtf;
  }


  /**
   * Creates a new ExamplePerson RecordBuilder.
   * @return A new ExamplePerson RecordBuilder
   */
  public static demo.ExamplePerson.Builder newBuilder() {
    return new demo.ExamplePerson.Builder();
  }

  /**
   * Creates a new ExamplePerson RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ExamplePerson RecordBuilder
   */
  public static demo.ExamplePerson.Builder newBuilder(demo.ExamplePerson.Builder other) {
    return new demo.ExamplePerson.Builder(other);
  }

  /**
   * Creates a new ExamplePerson RecordBuilder by copying an existing ExamplePerson instance.
   * @param other The existing instance to copy.
   * @return A new ExamplePerson RecordBuilder
   */
  public static demo.ExamplePerson.Builder newBuilder(demo.ExamplePerson other) {
    return new demo.ExamplePerson.Builder(other);
  }

  /**
   * RecordBuilder for ExamplePerson instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ExamplePerson>
    implements org.apache.avro.data.RecordBuilder<ExamplePerson> {

    private int id;
    private java.lang.CharSequence username;
    private java.lang.Object wtf;
    private java.lang.Object maybeWtf;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(demo.ExamplePerson.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.username)) {
        this.username = data().deepCopy(fields()[1].schema(), other.username);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.wtf)) {
        this.wtf = data().deepCopy(fields()[2].schema(), other.wtf);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.maybeWtf)) {
        this.maybeWtf = data().deepCopy(fields()[3].schema(), other.maybeWtf);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ExamplePerson instance
     * @param other The existing instance to copy.
     */
    private Builder(demo.ExamplePerson other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.username)) {
        this.username = data().deepCopy(fields()[1].schema(), other.username);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.wtf)) {
        this.wtf = data().deepCopy(fields()[2].schema(), other.wtf);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.maybeWtf)) {
        this.maybeWtf = data().deepCopy(fields()[3].schema(), other.maybeWtf);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Integer getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public demo.ExamplePerson.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public demo.ExamplePerson.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'username' field.
      * @return The value.
      */
    public java.lang.CharSequence getUsername() {
      return username;
    }

    /**
      * Sets the value of the 'username' field.
      * @param value The value of 'username'.
      * @return This builder.
      */
    public demo.ExamplePerson.Builder setUsername(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.username = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'username' field has been set.
      * @return True if the 'username' field has been set, false otherwise.
      */
    public boolean hasUsername() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'username' field.
      * @return This builder.
      */
    public demo.ExamplePerson.Builder clearUsername() {
      username = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'wtf' field.
      * @return The value.
      */
    public java.lang.Object getWtf() {
      return wtf;
    }

    /**
      * Sets the value of the 'wtf' field.
      * @param value The value of 'wtf'.
      * @return This builder.
      */
    public demo.ExamplePerson.Builder setWtf(java.lang.Object value) {
      validate(fields()[2], value);
      this.wtf = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'wtf' field has been set.
      * @return True if the 'wtf' field has been set, false otherwise.
      */
    public boolean hasWtf() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'wtf' field.
      * @return This builder.
      */
    public demo.ExamplePerson.Builder clearWtf() {
      wtf = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'maybeWtf' field.
      * @return The value.
      */
    public java.lang.Object getMaybeWtf() {
      return maybeWtf;
    }

    /**
      * Sets the value of the 'maybeWtf' field.
      * @param value The value of 'maybeWtf'.
      * @return This builder.
      */
    public demo.ExamplePerson.Builder setMaybeWtf(java.lang.Object value) {
      validate(fields()[3], value);
      this.maybeWtf = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'maybeWtf' field has been set.
      * @return True if the 'maybeWtf' field has been set, false otherwise.
      */
    public boolean hasMaybeWtf() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'maybeWtf' field.
      * @return This builder.
      */
    public demo.ExamplePerson.Builder clearMaybeWtf() {
      maybeWtf = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ExamplePerson build() {
      try {
        ExamplePerson record = new ExamplePerson();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.username = fieldSetFlags()[1] ? this.username : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.wtf = fieldSetFlags()[2] ? this.wtf : (java.lang.Object) defaultValue(fields()[2]);
        record.maybeWtf = fieldSetFlags()[3] ? this.maybeWtf : (java.lang.Object) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ExamplePerson>
    WRITER$ = (org.apache.avro.io.DatumWriter<ExamplePerson>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ExamplePerson>
    READER$ = (org.apache.avro.io.DatumReader<ExamplePerson>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
